# from langgraph.checkpoint.memory import MemorySaver
# from langgraph.graph import StateGraph, START,END
# from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
# from agent_graph.tool_postgres_sqlagent import  query_sqldb
# from agent_graph.tool_lookup_policy_rag import lookup_swiss_airline_policy
# from agent_graph.tool_tavily_search import load_tavily_search_tool
# from agent_graph.tool_stories_rag import lookup_stories
# from agent_graph.load_tools_config import LoadToolsConfig
# from agent_graph.agent_backend import State, BasicToolNode, route_tools, plot_agent_schema
# from langchain_groq import ChatGroq
# from langchain_core.messages import SystemMessage

# TOOLS_CFG = LoadToolsConfig()


# def build_graph():
#     """
#     Builds an agent decision-making graph by combining an LLM with various tools
#     and defining the flow of interactions between them.

#     This function sets up a state graph where a primary language model (LLM) interacts
#     with several predefined tools (e.g., databases, search functions, policy lookup, etc.).
#     The agent can invoke tools based on conditions and use their outputs to inform
#     further decisions. The flow involves conditional tool invocation, returning back
#     to the chatbot after tool execution to guide the next step.

#     Steps:
#     1. Initializes the primary language model (LLM) with tool-binding functionality.
#     2. Defines nodes in the graph where each node represents a specific action:
#        - Chatbot node: Executes the LLM with the given state and messages.
#        - Tools node: Runs the tool invocations based on the last message in the input state.
#     3. Implements conditional routing between the chatbot and tools:
#        - If a tool is required, it routes to the tools node.
#        - Otherwise, the flow ends.
#     4. Establishes connections between the chatbot and tools nodes to form the agent loop.
#     5. Uses a memory-saving mechanism to track and save checkpoints in the graph.

#     Returns:
#         graph (StateGraph): The compiled state graph that represents the decision-making process
#         of the agent, integrating the chatbot, tools, and conditional routing.

#     Components:
#         - `primary_llm`: The primary language model responsible for generating responses.
#         - `tools`: A list of tools including SQL queries, search functionalities, policy lookups, etc.
#         - `tool_node`: A node responsible for handling tool execution based on the chatbot's request.
#         - `chatbot`: A function that takes the state as input and returns a message generated by the LLM.
#         - `route_tools`: A conditional function to determine whether the chatbot should call a tool.
#         - `graph`: The complete graph with nodes and conditional edges.
#     """
#     # llm = HuggingFaceEndpoint(model=TOOLS_CFG.primary_agent_llm,
#     #                           task="text_generation",temperature=TOOLS_CFG.primary_agent_llm_temperature)
#     # primary_llm = ChatHuggingFace(llm=llm)
#     primary_llm = ChatGroq(model="openai/gpt-oss-120b")
#     graph_builder = StateGraph(State)
#     # Load tools with their proper configs
#     search_tool = load_tavily_search_tool(TOOLS_CFG.tavily_search_max_results)
#     tools = [search_tool,
#              lookup_swiss_airline_policy,
#              lookup_stories,
#              query_sqldb
#              ]
#     # Tell the LLM which tools it can call
#     primary_llm_with_tools = primary_llm.bind_tools(tools)
    
#      # -------------------------------
#     # 3. Define chatbot node
#     # -------------------------------
#     def chatbot_node(state: State):
#         # response = primary_llm_with_tools.invoke(state.messages)
#         # return {"messages": [response]}
#         messages = state.get("messages", [])
#         response = primary_llm_with_tools.invoke(messages)
#         return {"messages": [response]}

#     # -------------------------------
#     # 4. Tool execution node
#     # -------------------------------
#     tool_node = BasicToolNode(tools)

#     # -------------------------------
#     # 5. Build graph
#     # -------------------------------
#     graph = StateGraph(State)

#     graph.add_node("chatbot", chatbot_node)
#     graph.add_node("tools", tool_node)

#     graph.add_edge(START, "chatbot")

#     graph.add_conditional_edges(
#         "chatbot",
#         route_tools,          # decides tools vs end
#         {
#             "tools": "tools",
#             "end": END,
#         },
#     )

#     graph.add_edge("tools", "chatbot")

#     # -------------------------------
#     # 6. Compile & RETURN graph
#     # -------------------------------
#     memory = MemorySaver()

#     compiled_graph = graph.compile(checkpointer=memory)

#     return compiled_graph   # 🚨 THIS WAS MISSING

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph, START, END

from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, AIMessage

from agent_graph.tool_postgres_sqlagent import query_sqldb
from agent_graph.tool_lookup_policy_rag import lookup_swiss_airline_policy
from agent_graph.tool_tavily_search import load_tavily_search_tool
from agent_graph.tool_stories_rag import lookup_stories
from agent_graph.load_tools_config import LoadToolsConfig
from agent_graph.agent_backend import State, BasicToolNode

# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------
TOOLS_CFG = LoadToolsConfig()

SYSTEM_PROMPT = """
You are an intelligent assistant.

Rules:
- Use tools ONLY when required.
- If a tool answers the question, STOP.
- Do NOT repeat tool calls.
- After a successful SQL query, return the final answer in plain English.
- Never re-check schema unless explicitly asked.
"""


# ------------------------------------------------------------------
# Tool routing logic (CRITICAL)
# ------------------------------------------------------------------
def route_tools(state: State):
    """
    Decide whether to call tools or terminate.
    """
    messages = state.get("messages", [])
    if not messages:
        return "end"

    last = messages[-1]

    # If the model has produced a final answer → STOP
    if isinstance(last, AIMessage) and last.content:
        return "end"

    # If the model explicitly requested tools → CONTINUE
    if isinstance(last, AIMessage) and last.tool_calls:
        return "tools"

    return "end"


# ------------------------------------------------------------------
# Graph builder
# ------------------------------------------------------------------
def build_graph(groq_api_key: str = None, tavily_api_key: str = None, postgres_uri: str = None):
    """
    Builds a clean, loop-safe agent graph with optional custom credential overrides.
    """

    # -------------------------------
    # 1. Initialize LLM
    # -------------------------------
    if groq_api_key:
        llm = ChatGroq(model="openai/gpt-oss-120b", groq_api_key=groq_api_key)
    else:
        llm = ChatGroq(model="openai/gpt-oss-120b")

    # -------------------------------
    # 2. Load tools (MINIMAL SET)
    # -------------------------------
    search_tool = load_tavily_search_tool(
        TOOLS_CFG.tavily_search_max_results,
        api_key=tavily_api_key
    )

    tools = [
        query_sqldb,                    # ✅ single SQL entry point
        search_tool,
        lookup_swiss_airline_policy,
        lookup_stories,
    ]

    llm_with_tools = llm.bind_tools(tools)

    # -------------------------------
    # 3. Chatbot node
    # -------------------------------
    def chatbot_node(state: State):
        messages = state.get("messages", [])

        # Always inject system rules
        messages = [SystemMessage(content=SYSTEM_PROMPT)] + messages

        response = llm_with_tools.invoke(messages)
        return {"messages": [response]}

    # -------------------------------
    # 4. Tool execution node
    # -------------------------------
    tool_node = BasicToolNode(tools)

    # -------------------------------
    # 5. Build LangGraph
    # -------------------------------
    graph = StateGraph(State)

    graph.add_node("chatbot", chatbot_node)
    graph.add_node("tools", tool_node)

    graph.add_edge(START, "chatbot")

    graph.add_conditional_edges(
        "chatbot",
        route_tools,
        {
            "tools": "tools",
            "end": END,
        },
    )

    graph.add_edge("tools", "chatbot")

    # -------------------------------
    # 6. Compile graph
    # -------------------------------
    memory = MemorySaver()

    compiled_graph = graph.compile(checkpointer=memory)

    return compiled_graph
