import os
import sys
import json
import re

# Ensure src directory is in sys.path for internal imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from typing import List, Optional, Any, Dict
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyprojroot import here

from chatbot.load_config import LoadProjectConfig
from agent_graph.load_tools_config import LoadToolsConfig
from agent_graph.builld_full_graph import build_graph
from utils.app_utils import create_directory
from chatbot.memory import Memory

# Initialize configs and graph
PROJECT_CFG = LoadProjectConfig()
TOOLS_CFG = LoadToolsConfig()
create_directory("memory")

app = FastAPI(
    title="RAG_LLM_SQL Agentic AI API",
    description="Backend API wrapper for LangGraph Agent combining RAG, NL-SQL, and Web Search.",
    version="1.0.0"
)

# Enable CORS for local dev and production frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Default compiled LangGraph instance
default_agent_graph = build_graph()


class ChatRequest(BaseModel):
    message: str
    thread_id: Optional[str] = None
    groq_api_key: Optional[str] = None
    tavily_api_key: Optional[str] = None
    postgres_uri: Optional[str] = None


class ToolActivity(BaseModel):
    tool: str
    label: str
    status: str  # "completed", "running", "failed"
    details: Optional[str] = None


class RAGSource(BaseModel):
    title: str
    section: Optional[str] = None
    content: str


class WebSource(BaseModel):
    title: str
    url: str
    snippet: str


class ChatResponse(BaseModel):
    thread_id: str
    answer: str
    tool_used: str  # "sql" | "policy_rag" | "stories_rag" | "web_search" | "general"
    tool_activities: List[ToolActivity]
    sql_query: Optional[str] = None
    sql_data: Optional[List[Dict[str, Any]]] = None
    rag_sources: List[RAGSource] = []
    web_sources: List[WebSource] = []


TOOL_LABELS = {
    "query_sqldb": "PostgreSQL SQL Agent",
    "lookup_swiss_airline_policy": "Swiss Airline Policy RAG",
    "lookup_stories": "Stories Knowledge Base RAG",
    "tavily_search_results_json": "Tavily Web Search",
    "tavily_search": "Tavily Web Search"
}


@app.get("/health")
def health_check():
    """Health check endpoint returning system status."""
    return {
        "status": "ok",
        "service": "Agentic AI RAG-SQL-Web Backend",
        "version": "1.0.0"
    }


@app.post("/api/chat", response_model=ChatResponse)
def chat_endpoint(request: ChatRequest):
    """Processes user queries via the LangGraph state machine and returns rich structured responses."""
    if not request.message or not request.message.strip():
        raise HTTPException(status_code=400, detail="Message string cannot be empty.")

    thread_id = request.thread_id or TOOLS_CFG.thread_id
    config = {"configurable": {"thread_id": str(thread_id)}}

    try:
        # Determine whether to use custom user credentials or server default .env fallbacks
        if request.groq_api_key or request.tavily_api_key or request.postgres_uri:
            graph_inst = build_graph(
                groq_api_key=request.groq_api_key,
                tavily_api_key=request.tavily_api_key,
                postgres_uri=request.postgres_uri
            )
        else:
            graph_inst = default_agent_graph

        # Run graph execution
        result = graph_inst.invoke(
            {"messages": [("user", request.message)]},
            config
        )

        messages = result.get("messages", [])
        if not messages:
            raise HTTPException(status_code=500, detail="No output generated by agent.")

        # Extract final answer from last message
        final_message = messages[-1]
        raw_answer = getattr(final_message, "content", str(final_message))

        tool_activities: List[ToolActivity] = []
        rag_sources: List[RAGSource] = []
        web_sources: List[WebSource] = []
        sql_query: Optional[str] = None
        sql_data: Optional[List[Dict[str, Any]]] = None
        primary_tool_used = "general"

        # Inspect message history to discover tool invocations and outputs
        for msg in messages:
            # Check AIMessage tool calls
            tool_calls = getattr(msg, "tool_calls", None)
            if tool_calls:
                for tc in tool_calls:
                    t_name = tc.get("name", "")
                    label = TOOL_LABELS.get(t_name, t_name)
                    tool_activities.append(
                        ToolActivity(tool=t_name, label=label, status="completed")
                    )

                    if "sql" in t_name.lower():
                        primary_tool_used = "sql"
                    elif "policy" in t_name.lower():
                        primary_tool_used = "policy_rag"
                    elif "stories" in t_name.lower():
                        primary_tool_used = "stories_rag"
                    elif "search" in t_name.lower() or "tavily" in t_name.lower():
                        primary_tool_used = "web_search"

            # Check ToolMessage content for structured data
            msg_name = getattr(msg, "name", "")
            if msg_name:
                content = getattr(msg, "content", "")
                if isinstance(content, str):
                    try:
                        content_json = json.loads(content)
                    except Exception:
                        content_json = content

                if msg_name == "lookup_swiss_airline_policy":
                    passages = str(content).split("\n\n")
                    for p in passages:
                        if p.strip():
                            rag_sources.append(
                                RAGSource(title="Swiss Airline Policy", content=p.strip())
                            )
                elif msg_name == "lookup_stories":
                    passages = str(content).split("\n\n")
                    for p in passages:
                        if p.strip():
                            rag_sources.append(
                                RAGSource(title="Story Knowledge Base", content=p.strip())
                            )
                elif "tavily" in msg_name or msg_name == "tavily_search_results_json":
                    if isinstance(content, list):
                        for item in content:
                            if isinstance(item, dict):
                                web_sources.append(
                                    WebSource(
                                        title=item.get("title", "Web Result"),
                                        url=item.get("url", "#"),
                                        snippet=item.get("content", item.get("snippet", ""))
                                    )
                                )

        # Extract SQL query patterns if SQL tool was used
        if primary_tool_used == "sql" or "SELECT" in raw_answer.upper():
            sql_match = re.search(r"```sql\s*(.*?)\s*```", raw_answer, re.DOTALL | re.IGNORECASE)
            if sql_match:
                sql_query = sql_match.group(1).strip()
            elif "SELECT" in raw_answer.upper():
                lines = [l.strip() for l in raw_answer.split("\n") if "SELECT" in l.upper()]
                if lines:
                    sql_query = lines[0]

        # Log conversation memory
        try:
            chatbot_log = [(request.message, raw_answer)]
            Memory.write_chat_history_to_file(
                gradio_chatbot=chatbot_log,
                folder_path=PROJECT_CFG.memory_dir,
                thread_id=str(thread_id)
            )
        except Exception as log_err:
            print("Memory logging warning:", log_err)

        return ChatResponse(
            thread_id=str(thread_id),
            answer=raw_answer,
            tool_used=primary_tool_used,
            tool_activities=tool_activities,
            sql_query=sql_query,
            sql_data=sql_data,
            rag_sources=rag_sources,
            web_sources=web_sources
        )

    except Exception as e:
        print("API Chat Error:", e)
        raise HTTPException(status_code=500, detail=f"Agent execution error: {str(e)}")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("src.api:app", host="0.0.0.0", port=8000, reload=True)
